### ISSUE TITLE
Índice para ejercicios propuestos

### ISSUE THREAD

**Issue by xourge** [JulioApazaZhukov/PB_UDEP#1]
agregar un índice para encontrar rápidamente los ejercicios

**Comment by JulioApazaZhukov** [comment]
Nuevo archivo creado en markdown con todos los enunciados que se vieron hasta hoy. Cada clase es un subtítulo, y el contenido son los respectivos enunciados.

![image](https://github.com/user-attachments/assets/72cf353d-1f33-4535-ac94-d089c3e69013)

https://github.com/JulioApazaZhukov/PB_UDEP/blob/main/Enunciados%20de%20PB%202024-II.md
