### ISSUE TITLE
Enunciados para ejercicios propuestos

### ISSUE THREAD

**Issue by xourge** [JulioApazaZhukov/PB_UDEP#2]
agregar enunciados a los ejercicios

**Comment by JulioApazaZhukov** [comment]
Buenas tardes profesor,

Los enunciados de los ejercicios los estoy colocando en archivos markdown con el número de la clase para agruparlos. Esto lo he hecho pensando sobre todo para que sea fácilmente visualizado en VSCode con la pantalla dividida.
![image](https://github.com/user-attachments/assets/28aceeab-f7eb-4bfc-bf4b-f7e2d5b611ea)
